"""GlycoQuant visual design tokens — publication-grade scientific figures.

A single source of truth for palettes, typography, and Plotly layout.
All charts generated by ``glycoquant.viz.*`` use these settings so
figures are consistent whether shown in the React frontend, a Jupyter
notebook, or exported for a manuscript.

Design principles:
- ColorBrewer Set2 for categorical data (Nature Methods standard)
- RdBu diverging (centered on zero) for correlation matrices
- Viridis sequential for feature intensities
- Inter font for all text
- Transparent backgrounds (cards provide the white)
- Minimal gridlines, no modebar
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# ColorBrewer palettes (perceptually uniform, colorblind-safe)
# ---------------------------------------------------------------------------

# Set2 — qualitative, up to 8 categories (Nature Methods, Cell Systems standard)
COLORBREWER_SET2 = [
    "#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3",
    "#a6d854", "#ffd92f", "#e5c494", "#b3b3b3",
]

# Dark2 — qualitative, higher contrast variant
COLORBREWER_DARK2 = [
    "#1b9e77", "#d95f02", "#7570b3", "#e7298a",
    "#66a61e", "#e6ab02", "#a6761d", "#666666",
]

# Channel colors (same as frontend CSS variables)
CHANNEL_COLORS = {
    "dapi": "#2166ac",
    "glycocalyx": "#1b7837",
    "yap": "#762a83",
    "paxillin": "#b35806",
    "actin": "#4d4d4d",
}

# ---------------------------------------------------------------------------
# Typography
# ---------------------------------------------------------------------------

FONT_FAMILY = "Inter, -apple-system, BlinkMacSystemFont, sans-serif"
FONT_MONO = "JetBrains Mono, SF Mono, Consolas, monospace"

# ---------------------------------------------------------------------------
# Color tokens
# ---------------------------------------------------------------------------

TEXT_PRIMARY = "#111827"     # gray-900
TEXT_SECONDARY = "#6b7280"  # gray-500
TEXT_MUTED = "#9ca3af"      # gray-400
GRID_COLOR = "#f3f4f6"      # gray-100
ZEROLINE_COLOR = "#e5e7eb"  # gray-200
ACCENT_BLUE = "#2563eb"     # blue-600
ACCENT_BLUE_DESAT = "#6baed6"  # desaturated blue for bars
ACCENT_BLUE_LIGHT = "#93c5fd"  # light blue for score bars


# ---------------------------------------------------------------------------
# Backward-compatible Palette dataclass (used by radial_profile.py etc.)
# ---------------------------------------------------------------------------

from dataclasses import dataclass


@dataclass(frozen=True)
class Palette:
    bg_base: str = "#FFFFFF"
    bg_subtle: str = "#F8FAFC"
    bg_muted: str = "#F1F5F9"
    bg_elevated: str = "#FFFFFF"
    border_subtle: str = "#E2E8F0"
    border_strong: str = "#CBD5E1"
    text_primary: str = TEXT_PRIMARY
    text_secondary: str = TEXT_SECONDARY
    text_muted: str = TEXT_MUTED
    accent_primary: str = ACCENT_BLUE
    accent_brand: str = "#0D9488"
    accent_violet: str = "#7C3AED"
    accent_amber: str = "#F59E0B"
    success: str = "#16A34A"
    warning: str = "#EA580C"
    error: str = "#DC2626"
    info: str = ACCENT_BLUE


PALETTE = Palette()


def get_plotly_layout_template() -> dict:
    """Publication-grade Plotly layout template.

    Apply via ``fig.update_layout(**get_plotly_layout_template())``
    in every ``glycoquant.viz`` factory.
    """
    return {
        "paper_bgcolor": "rgba(0,0,0,0)",
        "plot_bgcolor": "rgba(0,0,0,0)",
        "font": {
            "family": FONT_FAMILY,
            "color": TEXT_SECONDARY,
            "size": 11,
        },
        "title": {
            "font": {
                "family": FONT_FAMILY,
                "size": 13,
                "color": TEXT_PRIMARY,
            },
            "x": 0.0,
            "xanchor": "left",
        },
        "xaxis": {
            "gridcolor": GRID_COLOR,
            "zerolinecolor": ZEROLINE_COLOR,
            "linecolor": ZEROLINE_COLOR,
            "tickfont": {"color": TEXT_MUTED, "size": 10, "family": FONT_FAMILY},
            "title": {"font": {"color": TEXT_SECONDARY, "size": 11}},
        },
        "yaxis": {
            "gridcolor": GRID_COLOR,
            "zerolinecolor": ZEROLINE_COLOR,
            "linecolor": ZEROLINE_COLOR,
            "tickfont": {"color": TEXT_MUTED, "size": 10, "family": FONT_FAMILY},
            "title": {"font": {"color": TEXT_SECONDARY, "size": 11}},
        },
        "legend": {
            "bgcolor": "rgba(255,255,255,0.9)",
            "font": {"color": TEXT_SECONDARY, "size": 10},
        },
        "colorway": COLORBREWER_SET2,
        "margin": {"l": 50, "r": 20, "t": 30, "b": 50},
    }
